language: c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install bc

script:
  - mkdir toolchain
  - pushd toolchain
  - git clone --depth=1 https://github.com/raspberrypi/tools
  - export PATH=`pwd`/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/:$PATH
  - popd
  - mkdir linux
  - pushd linux
  - git clone --depth=1 https://github.com/raspberrypi/linux.git
  - export ARCH=arm
  - export CROSS_COMPILE=arm-linux-gnueabihf-
  - cd linux
  - export KERNEL=kernel7
  - export NUM_CPU_CORES=`/usr/bin/nproc`
  - make -j$NUM_CPU_CORES bcm2709_defconfig
  - make -j$NUM_CPU_CORES zImage modules
  - make -j$NUM_CPU_CORES M=$PWD/../../bal
